config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v3 do
      get 'cupcakes/index'
    end
  end
  get 'subscriptions/index'
  get 'subscriptions/create'
  get 'subscriptions/new'
  get 'subscriptions/show'
  get 'subscriptions/update'
  devise_for :users
  get 'pages/home'
  get 'settings/home'

  mount Flipper::UI.app(Flipper.instance) => '/flipper'

  resources :dashboard

  resources :notifications

  resources :employers do
    get 'get_employers'
    resources :accounts, only: [:index] do 
    end
    resources :wage_reports, shallow: true do
      resources :wage_entries
    end
  end

  resources :tpas do
    get 'get_tpas'
  end

  # resources : do


  # end


  resources :settings do
    post 'create_role', to: 'settings#create_role', as: 'create_role'
    post 'create_key', to: 'settings#create_key', as: 'create_key'
    post 'create_permissions', to: 'settings#create_permissions', as: 'create_permissions'
    get 'get_roles', to: 'settings#get_roles'
    get 'get_keys', to: 'settings#get_keys'
    get 'get_permissions', to: 'settings#get_permissions'
    delete 'remove_role_and_permissions', to: 'settings#remove_role_and_permissions'
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wages/wage_report.rb
module Wages

	TAXABLE_WAGES_MAXIMUM = 9_000
	
	class WageReport
	  include Mongoid::Document
	  include Mongoid::Timestamps

	  SUBMISSION_KINDS 				= [:original, :amended, :estimated]
	  FILING_METHOD_KINDS 		= [:upload, :manual_entry, :no_wages]

	  STATUS_KINDS 				= [:processed, :submitted, :terminated]

		# attr_readonly :submission_kind, :submitted_at

	  field :submitted_at, 							type: Time
	  field :submitted_by_id, 					type: BSON::ObjectId
	  field :user_account_id, 					type: BSON::ObjectId

	  field :status,										type: Symbol
	  field :submission_kind,						type: Symbol
	  field :filing_method_kind,				type: Symbol

	  field :state_total_gross_wages, 	type: BigDecimal

	  field :state_ui_total_wages, 			type: BigDecimal
	  field :state_ui_taxable_wages, 		type: BigDecimal
	  field :state_ui_excess_wages, 		type: BigDecimal

	  field :ui_tax_amount, 			type: BigDecimal
	  field :ui_admin_fee_amount,	type: BigDecimal
	  field :ui_interest_amount, 	type: BigDecimal
	  field :ui_penalty_amount, 	type: BigDecimal

	  field :ui_total_due, 							type: BigDecimal
	  field :ui_paid_amount, 						type: BigDecimal
	  field :ui_amount_due, 						type: BigDecimal

	  field :total_employees,						type: Integer

	  embeds_many	:wage_entries,
                class_name: 'Wages::WageEntry'
    
    # embeds_many	:wages,
	  # 						class_name: 'Wages::Wage'

	  belongs_to	:organization_party,
	  						class_name: 'Parties::OrganizationParty'

	  has_many 		:timespans, 
	  						class_name: 'Timespans::Timespan'

	  validates_presence_of :organization_party, :filing_method_kind,
	  											:submission_kind #:total_wages, 
	  											# :excess_wages, :taxable_wages


	  belongs_to	:timespan, 
	  						class_name: 'Timespans::Timespan'

	  # validates_presence_of :organization_party, :timespan, :wage_entries, :filing_method_kind,
	  # 											:submission_kind, :total_wages, 
	  # 											:excess_wages, :taxable_wages

    index({ organization_party_id: 1, timespan_id: 1 })
    index({ timespan_id: 1 })


    def set_state_wages
    	write_attributes(sum_all_state_wages)
    end

    def sum_state_total_wages
      wage_entries.map(&:wage).compact.reduce(0.0) do |subtotal, wage|
         subtotal += wage.state_total_gross_wages || 0
        end
	  end

    def sum_state_excess_wages
     if (sum_state_total_wages - 9000) < 0 
      0 
     else
      sum_state_total_wages - 9000 
     end
	  end

    def sum_state_taxable_wages
      ee_count =  wage_entries.size
      total_taxable =  (9000 * ee_count)
      total = wage_entries.map(&:wage).compact.reduce(0.0) do  |subtotal, wage| 
        subtotal += wage.state_taxable_wages || 0 
      end
      if total > total_taxable
        total_taxable
      else  
        total
      end
    end
    
    def ui_total_due
        sum_state_total_wages - sum_state_excess_wages
    end


    def self.current_reports(org)
     quarter = org.wage_reports.sort{|a,b| b.timespan.begin_on - a.timespan.begin_on}.first
    end
          
    def ui_paid_amount
      0
    end

    def self.multi_report_totals(reports)
     total_wages =  reports.reduce(0.0) do |subtotal, total_wages|
        subtotal += total_wages.sum_state_total_wages
      end

      total_taxable =  reports.reduce(0.0) do |subtotal, total_wages|
        subtotal += total_wages.sum_state_taxable_wages
      end

      total_excess =  reports.reduce(0.0) do |subtotal, total_wages|
        subtotal += total_wages.sum_state_excess_wages
      end

      [total_wages,total_taxable, total_excess]
    end

      
    def sum_state_ui_total_wages
      sum_state_total_wages
    end

	  # Calculate all wage values in one pass -- higher performance on large wage reports
    def sum_all_state_wages
      wage_entries.map do | wage_entry |
        total_wages 	+= wage_entry.state_total_gross_wages 
        excess_wages 	+= wage_entry.state_qtr_total_gross_wages
        taxable_wages += wage_entry.state_qtr_total_gross_wages 
        { state_total_wages: total_wages, state_excess_wages: excess_wages, state_taxable_wages: taxable_wages }
      end
    end

	  def sum_employees
	  	wage_entries.compact.uniq.size
    end

    def self.latest_timespan(org)
      filter =  self.find_and_filter_wage_reports(org)
      if filter.present? 
        filter[0].timespan
      else  
        []
      end

    end

    def self.find_and_filter_wage_reports(org)
        org.wage_reports.sort{|a,b|b.timespan.begin_on - a.timespan.begin_on} 
    end

    def self.current_quarters(org)
      quarters = Timespans::Timespan.current_quarters.map(&:id)
      puts quarters.inspect
      puts org.wage_reports.map(&:timespan).inspect
      reports = quarters.map{|q| org.wage_reports.select{|a|a.timespan.id == q}.first}
     if reports.compact.present?
      reports.map(&:timespan) 
     else 
      []
     end

   end

    def self.find_and_filter_wage_reports_by_quarter(org, quarter)
      org.wage_reports.select{|d|d.timespan.begin_on == quarter.begin_on}.sort{|a,b|  b.submitted_at - a.submitted_at} if quarter.present?
    end
    

	  private 

	  def set_total_employees
	  	write_attribute(:total_employees, sum_employees)
	  end

	end
end

app/controllers/wage_reports_controller.rb
class WageReportsController <  ApplicationController
  layout 'two_column'
  before_action :authenticate_user!

  def index
    @organization = Parties::OrganizationParty.find(params[:employer_id])
    @all_quarters = Timespans::Timespan.all_quarters
    @current_quarters = Wages::WageReport.current_quarters(@organization)
    @latest_timespan = Wages::WageReport.latest_timespan(@organization)
    @current_timespan =  Timespans::Timespan.current_timespan
    @current_reports =  Wages::WageReport.find_and_filter_wage_reports_by_quarter(@organization, @latest_timespan)
    @report= Wages::WageReport.new
    @org_reports =  Wages::WageReport.find_and_filter_wage_reports(@organization)[2..5] || []
    @last_year_totals = Wages::WageReport.multi_report_totals(@org_reports)
  end

  def new
    @report = Wages::WageReport.new 
    @organization = Parties::OrganizationParty.find(params[:employer_id])
    if params[:report] == "new"
      Wages::WageReportFactory.set_current_report(nil)
    end
    @current_report = Wages::WageReportFactory.get_current_report
    @entries = @current_report.try(:wage_entries)
  end

  def show 
    @current_report = Wages::WageReport.find(params[:id])
    @organization = @current_report.organization_party
    @entries = @current_report.wage_entries.compact
    @entry  =  @current_report.wage_entries.new
    @people = Parties::PersonParty.all
  end

  def edit 
    @report = Wages::WageReport.find(params[:id])
    @organization = @report.organization_party
    @amend_reasons = Wages::WageEntry::AMEND_REASONS
    @entries = @report.wage_entries.sort{|a,b| b.wage.state_total_gross_wages - a.wage.state_total_gross_wages}
    @entry  =  @report.wage_entries.new
    @submission_kinds = Wages::WageEntry::SUBMISSION_KINDS
  end

  def create 
    @report = Wages::WageReport.new
    if params[:commit] == "Add Entry"
      Wages::WageReportFactory.create_report_and_add_entries(params)
    end
    @organization = Parties::OrganizationParty.find(params[:employer_id])
    redirect_to new_employer_wage_report_path(@organization)
  end

  def destroy
    report = Wages::WageReport.find(params[:id])
    entry = report.wage_entries.find(params[:entry])
    entry.destroy 
    redirect_to edit_wage_report_path(report)
  end

  def update
    @report = Wages::WageReport.find(params[:id])
    if params[:commit] == "Cancel" ||  params[:commit] == "Save"
      redirect_to employer_wage_reports_path(@report.organization_party)
    else
      Wages::WageReportFactory.amend(@report, params)
      redirect_to employer_wage_reports_path(@report.organization_party)
    end
  end
end

app/views/wage_reports/_at_a_glance.html.erb
<div class="card-body">
  <div class="card">      <div class="accordion md-accordion" id="accordionEx" role="tablist" >
        <a data-toggle="collapse" data-parent="#accordionEx"href="#at-a-glance" >
    <li class="list-group-item "id="card-header">Quarterly Calculations </li>
    </a>
    <div class = "collapse hide" id = "at-a-glance">
        <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
      <thead>
        <tr class =  "at-a-glance">
          <td class="td-sm">Report Details
          </td>
          <td class="td-sm">Quarter 1
          </td>
          <td class="td-sm">Quarter 2 
          </td>
          <td class="td-sm">Quarter 3 
          </td>
          <td class="td-sm">Quarter 4
          </td>
        </tr>
      </thead>
      <tbody>
        <tr>
            <td>Report Type</td>
            <td>Amended</td>
            <td>Original</td>
            <td>Amended</td>
            <td>Original</td>
            <td></td>
        </tr>
        <tr>
            <td>Submitted on</td>
            <td>1/23/2018</td>
            <td>4/23/2018</td>
            <td>8/23/2018</td>
            <td>12/23/2018</td>
        </tr>
        <tr>
            <td> Submitted By</td>
            <td>IdeaCrew</td>
            <td>IdeaCrew</td>
            <td>IdeaCrew</td>
            <td>IdeaCrew</td>
                        <td></td>

        </tr>
        <tr>
            <td> User Name</td>
            <td>Dan Thomas</td>
            <td>Angus Irvine</td>
            <td>Dan Thomas</td>
            <td>Dan Thomas</td>
                        <td></td>
        </tr>
      </tbody>
        <thead>
          <tr class = 'at-a-glance'>
          <td class="td-sm">Quarterly Wages
            </td>
            <td class="td-sm">Quarter 1
            </td>
            <td class="td-sm">Quarter 2 
            </td>
            <td class="td-sm">Quarter 3 
            </td>
            <td class="td-sm">Quarter 4
            </td>
            <td class="td-sm">Total
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Total Wages</td>
            <% @org_reports.each do |report|%>
              <td><%=number_to_currency(report.sum_state_total_wages)%></td>
            <% end%>
              <td><%=number_to_currency(@last_year_totals[0])%></td>
          </tr>
          <tr>
              <td>Taxable Wages</td>
            <% @org_reports.each do |report|%>
              <td><%=number_to_currency(report.sum_state_taxable_wages)%></td>
            <% end%>
              <td><%=number_to_currency(@last_year_totals[1])%></td>
          </tr>
          <tr>
            <td>Excess Wages</td>
            <% @org_reports.each do |report|%>
             <td><%=number_to_currency(report.sum_state_excess_wages)%></td>
            <% end%>
            <td><%=number_to_currency(@last_year_totals[2])%></td>
           </tr>
      </tbody>

      <thead>
        <tr class = 'at-a-glance'>
        <td class="td-sm">Contributions
          </td>
          <td class="td-sm">Quarter 1
          </td>
          <td class="td-sm">Quarter 2 
          </td>
          <td class="td-sm">Quarter 3 
          </td>
          <td class="td-sm">Quarter 4
          </td>
          <td class="td-sm">Total
            </td>
          </td>
        </tr>
      </thead>
        <tbody>
          <tr>
              <td>UI Tax</td>
              <td><%=number_to_currency(110)%></td>
              <td><%=number_to_currency(130)%></td>
              <td><%=number_to_currency(124)%></td>
              <td><%=number_to_currency(220)%></td>
              <td><%=number_to_currency(584)%></td>
          </tr>
          <tr>
              <td>Administrative Assesment  </td>
              <td><%=number_to_currency(115)%></td>
              <td><%=number_to_currency(115)%></td>
              <td><%=number_to_currency(115)%></td>
              <td><%=number_to_currency(115)%></td>
              <td><%=number_to_currency(460)%></td>
          </tr>
          <tr>
              <td>Interest</td>
              <td><%=number_to_currency(0)%></td>
              <td><%=number_to_currency(00)%></td>
              <td><%=number_to_currency(00)%></td>
              <td><%=number_to_currency(00)%></td>
              <td><%=number_to_currency(0)%></td>
           </tr>
          <tr>
              <td>Penalty</td>
              <td><%=number_to_currency(0)%></td>
              <td><%=number_to_currency(0)%></td>
              <td><%=number_to_currency(0)%></td>
              <td><%=number_to_currency(0)%></td>
              <td><%=number_to_currency(0)%></td>
          </tr>
      </tbody>

  
    </table>
  </div>
  </div>
  </div>
</div>

app/views/wage_reports/_latest_report.html.erb
<% if @organization.wage_reports.present?%>
<div class="card-body">
  <div class="card">
    <li class="list-group-item"id="card-header">Latest Report -  <%= "#{@latest_timespan.title}"%> </li>
    <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
      <thead>
        <tr>
          <td class="td-sm">Submitted At
          </td>
          <td class="td-sm">Submission Kind
          </td>
          <td class="td-sm">Total Wages
          </td>
          <td class="td-sm">Taxable Wages
          </td>
          <td class="td-sm">Excess Wages
          </td>
          <td class="td-sm"> Administrative Assessment
          </td>        
            <td class="td-sm">Interest
          </td>       
             <td class="td-sm">Penalty
          </td>
          <td class="td-sm">Actions
          </td>
        </tr>
      </thead>
      <tbody>
        <% @current_reports.each do |current_report|%>
        <tr>
          <td><%= link_to "#{current_report.submitted_at.to_date}", wage_report_path(current_report), :class => "card-header"%></td>
          <td><%=current_report.submission_kind.capitalize%></td>
          <td><%=number_to_currency(current_report.sum_state_total_wages)%></td>
          <td><%=number_to_currency(current_report.sum_state_taxable_wages)%></td>
          <td><%=number_to_currency(current_report.sum_state_excess_wages)%></td>
          <td><%=number_to_currency(0)%></td>    
          <td><%=number_to_currency(0)%></td>
          <td><%=number_to_currency(0)%></td>
          <td> <%=link_to 'Amend', edit_wage_report_path(current_report), :class => "btn btn-outline-primary btn-rounded ", :id => "plus"  %></td>
        </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

<%else %>


<div class="card-body">
  <div class="card">
    <li class="list-group-item"id="card-header">Latest Reports </li>
    <div class = "no-reports">
    No Current Reports
    </div>

  </div>
</div>


<%end%>

app/views/wage_reports/_new_report.html.erb
<div class="card-body">
  <div class="card">
      <div class="accordion md-accordion" id="accordionEx" role="tablist" >
        <a data-toggle="collapse" data-parent="#accordionEx" >
            <li class="list-group-item" id="card-header">Start a new Wage Report </li>
        </a>
          <div id= "new-report" role="tabpanel" aria-labelledby="headingOne1" data-parent="#accordionEx">
            <div>
              <%= radio_button_tag :filing_method_kind, 'upload',  :class => 'radio' %> 
              <%= label :filing_method_kind, 'upload' %>
            </div>
            <div>
              <%= radio_button_tag :filing_method_kind, 'no_wages', :class => 'radio' %>
              <%= label :filing_method_kind, 'no_wages' %>
            </div>
            <div>
              <%= radio_button_tag :filing_method_kind, 'manual_entry', :checked => true, :class => 'radio' %>
              <%= label :filing_method_kind, 'manual_entry' %>
     
            </div>
            <div>
              <%= label :Quarter, "Quarter:" %>
              <%= select_tag "quarter" , options_for_select([@current_timespan.title, "2019 Q2", "2019 Q3","2019 Q4"], @current_timespan.title)%>

            </div>
            <div class = 'start-report-button btn' id = "create-report-btn">
            <%= link_to 'Create Report', controller: 'wage_reports', action: "new", employer_id: @organization.id, report: "new", method: :get%>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/wage_reports/_new_wage_report_new_entry.html.erb
    <div class="card">
            <li class="list-group-item" id = "card-header"> Add Wage Entries </li>
      <div class="" id="new-entry" role="tablist" >
            <%= form_for @report, url: employer_wage_reports_path(@organization), method: :post do |f| %>
              <%= f.fields_for :new_wage_entry do |field| %>
              <div class= 'card-body'>
                <div class="row ">
                  <div class = "col">
                  <%=f.hidden_field :report_id,:value => @report.id%>
                    <%= field.text_field :person_first_name, placeholder:"Employee First Name", required: true, :class =>" input form-control" %>
                  </div>
                  <div class = "col">
                    <%= field.text_field :person_last_name, placeholder: "Employee Last Name",required: true, :class =>" input form-control" %>
                  </div>
                  <div class="col">
                    <%= field.number_field :ssn, placeholder:"SSN", required: true,:class =>"input form-control" %>
                  </div>
                  <div class="col">
                    <%= field.number_field :state_total_gross_wages, placeholder:"UI Wages Paid", required: true,:class =>"input form-control" %>
                  </div>
                  <% end %>
              </div>
              <%= f.submit 'Add Entry', :class =>"btn btn-outline-primary btn-rounded",:id => "start-report" %>
        </div>
      </div>
    </div>
  </div>
</div>
        <% end %>

app/views/wage_reports/_new_wage_report_show.html.erb
<%if @current_report.present?  %>
   <%if params[:action] == "new"%>
    <div class = "page-footer card-body">
      <div class = "card report-details" >
        <div class="accordion md-accordion" id="accordionEx" role="tablist" >
          <div class="card-header" id= "card-header"role="tab">
              Wage Entries
          </div>
          </div>
        <%= render :partial => 'wage_report_show_entries' %>
        <%= render :partial => 'wage_report_show_footer' %>
        <%else%>
        <%= render :partial => 'wage_report_show_overview' %>
      <% end%>
    </div>
  </div>
<% end%>

app/views/wage_reports/_older_reports.html.erb
<div class="card-body">
<div class="card">
  <li class="list-group-item" id="card-header">Older Reports Versions </li>
  <% @current_quarters.reverse.compact.each do |quarter|%>
  <div class="accordion md-accordion" id="accordionEx" role="tablist" >
    <div class="card-header" role="tab">
      <a data-toggle="collapse" data-parent="#accordionEx" href="#<%="#{quarter.begin_on}"%>"
        <li class="list-group-item"> <%= "#{quarter.title}"%></li>
      </a>
    </div>
    <div id= <%="#{quarter.begin_on}"%> class="collapse hide" role="tabpanel" aria-labelledby="headingOne1" data-parent="#accordionEx">
      <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th class="th-sm">Status
          </th>
          <th class="th-sm">Submission Method
          </th>
          <th class="th-sm">Total Wages
          </th>
          <th class="th-sm">Taxable Wages
          </th>
          <th class="th-sm">Excess Wages
          </th>
          <th class="th-sm">Actions
          </th>
        </tr>
      </thead>
      <tbody>
      <% Wages::WageReport.find_and_filter_wage_reports_by_quarter(@organization,quarter).each do |report|%>
          <tr>
            <td><%= link_to "#{report.status.capitalize}", wage_report_path(report)%></td>
            <td><%=report.submission_kind.capitalize%></td>
            <td>$<%=report.sum_state_total_wages%></td>
            <td>$<%=report.sum_state_taxable_wages%></td>
            <td>$<%=report.sum_state_excess_wages%></td>
            <td>          
              <%=link_to 'Amend', edit_wage_report_path(report), :class => "btn btn-outline-primary btn-rounded ", :id => "plus"  %>
            </td>
          </tr>
          <%end%>
      </tbody>
    </table>
  </div>
  <%end%>
</div>

app/views/wage_reports/_wage_report_show_entries.html.erb
    <table  class="table table-striped  " id="new-entry">
      <thead>
        <tr>
          <td class="">Employee</td>
          <td class="td-sm">Submission Kind</td>
          <td class="td-sm">Submitted At</td>
          <td class="td-sm">UI Wages Paid</td>
          <td class="td-sm">Amend Reason</td>
      </tr>
      </thead>
      <tbody>
        <% @entries.each do |entry| %>
          <tr>
            <td><%= entry.try(:wage).try(:person_party).try(:current_first_name) + " " + entry.try(:wage).try(:person_party).try(:current_last_name)%></td>
            <td scope="row"><%= entry.submission_kind.capitalize%></td>
            <td scope="row"><%= entry.submitted_at.to_date%></td>
            <td>$ <%= entry.try(:wage).try(:state_total_gross_wages)%></td>
            <td> <%= entry.amend_reason.capitalize%></td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/wage_reports/_wage_report_show_footer.html.erb
  <div class = "page-footer card-body">
    <div class = "card report-details" >
      <div class="accordion md-accordion" id="accordionEx" role="tablist" >
        <div class="card-header" id= "card-header"role="tab">
            Wage Report Overview
        </div>
          <div class = 'row'>
            <div class = 'col'>
              <p  class="data-header">Total State Gross Wages</p>
                <p ><%=number_to_currency(@current_report.sum_state_total_wages)%></p>
            </div>
            <div class = 'col'>
              <p class="data-header">Total State UI Wages</p>
              <p><%=number_to_currency(@current_report.sum_state_ui_total_wages)%></p>
             </div>
            <div class ='col'>
              <p class="data-header"> State UI Taxable Wages</p>
              <p><%=number_to_currency(@current_report.sum_state_taxable_wages)%></p>
              </div>
            <div class = 'col'>
              <p class="data-header"> State UI Excess Wages</p>
              <p><%=number_to_currency(@current_report.sum_state_excess_wages)%></p>
            </div>
            <div class = 'col'>
              <p class="data-header"> Total Employees</p>
              <p><%=@current_report.sum_employees%></p>
            </div>
      </div>
  </div>
</div>
<%= link_to 'Submit', wage_report_path(@current_report),:class => "btn btn-outline-primary btn-rounded ", :id => "start-report" %>
<%= link_to 'Save', wage_report_path(@current_report),:class => "btn btn-outline-primary btn-rounded ", :id => "start-report" %>
<%= link_to 'Cancel', employer_wage_reports_path(@organization),:class => "btn btn-outline-primary btn-rounded ", :id => "start-report" %>

app/views/wage_reports/edit.html.erb
<div class="card-body">
    <div class="card">
      <div class="card-header " id= "card-header" >Amend Report </div>
          <div class= 'row edit-wage-report-card'>
            <div class = 'col  edit-wage-report-card'>Employee</div>
            <div class = 'col'>SSN</div>
            <div class = 'col'>UI Wages Paid</div>
            <div class = 'col'>Amend Reason</div>
            <div class = 'col'>Actions</div>
          </div>
      <div class="card">
        <div class="card-body">
           <%= form_for @report, url: wage_report_path(@report), method: :put do |f| %>
            <% @entries.each do |entry| %>
              <%= f.fields_for "wage_entries[]", entry do |wage_entry_field| %>
                <%= wage_entry_field.fields_for :wage, entry.wage do |wage_field| %>
                  <%= wage_field.hidden_field :id %>
                  <div class="row">
                    <div class="col">
                      <%="#{entry.try(:wage).try(:person_party).try(:current_first_name) +" " + entry.try(:wage).try(:person_party).try(:current_last_name) }" %>
                    </div>
                    <div class = 'col '>
                      <%= "#{entry.wage.person_party.hide_ssn}"%>
                    </div>              
                    <div class= 'col'>
                      <%= wage_field.text_field :state_total_gross_wages, :class =>" input form-control" %>
                    </div>         
                      <div class= 'col destroy-entry'>
                      <%= wage_entry_field.select "amend_reason", options_for_select(@amend_reasons[0..5] ) %>
                      </div>
                      <div class= 'col destroy-entry'>
                      <%= link_to "X", wage_report_path(@report, :entry => entry.id), :method => :delete, :class =>"start-report" %>
                    </div>        
                  </div>
              <%end%>
          <%end%>
        <%end%>
          <%= f.fields_for :new_wage_entry do |field| %>
            <div class="row ">
              <div class = "col">
              <%= field.text_field :person_first_name, placeholder:"Employee First Name", :class =>" input form-control" %>
              </div>
              <div class = "col">
              <%= field.text_field :person_last_name, placeholder: "Employee Last Name", :class =>" input form-control" %>
              </div>
              <div class="col">
                <%= field.number_field :state_total_gross_wages, placeholder:"UI Wages Paid",:class =>"input form-control" %>
              </div>
              <div class="col">
                  <%= field.number_field :ssn, placeholder:"SSN", :class =>"input  form-control" %>
              </div>
              <div class="col">
                  <%= select_tag :amend_reason, options_for_select(@amend_reasons) %>
              </div>
              <% end %>
              </div>
       <div id= "button-row"> 
        <%= f.submit 'Amend Report', :class =>"btn btn-outline-primary btn-rounded",:id => "start-report" %>
        <%= f.submit 'Cancel', :class =>"btn btn-outline-primary btn-rounded input", :id => "start-report"  %>
        <%= f.submit 'Save', :class =>"btn btn-outline-primary btn-rounded input ",:id => "start-report" %>
       </div>
      <% end %>
    </div>
  </div>

app/views/wage_reports/index.html.erb
<div class="card">
  <div class="card-header" id= "card-header"><%= @organization.legal_name %> Wage Reports</div>
  <%= render :partial => "new_report" %>
  <%= render :partial => "latest_report" %>
  <%if @organization.wage_reports.count >= 4 %>
  <%= render :partial => "at_a_glance" %>

  <%= render :partial => "older_reports" %>
  <% elsif @organization.wage_reports.count > 1 && @current_quarters.present?%>
  <%= render :partial => "older_reports" %>
  <%end%>
  </div>
</div>

app/views/wage_reports/new.html.erb
<div class="card">
  <div class="card-header" id= "card-header" >New Wage Report </div>
    <div class="card-body">
      <div class= 'card'>
        <%= render :partial => "new_wage_report_new_entry"%>
        <%= render :partial => "new_wage_report_show"%>
    </div>
  </div>
</div>