config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v3 do
      get 'cupcakes/index'
    end
  end
  get 'subscriptions/index'
  get 'subscriptions/create'
  get 'subscriptions/new'
  get 'subscriptions/show'
  get 'subscriptions/update'
  devise_for :users
  get 'pages/home'
  get 'settings/home'

  mount Flipper::UI.app(Flipper.instance) => '/flipper'

  resources :dashboard

  resources :notifications

  resources :employers do
    get 'get_employers'
    resources :accounts, only: [:index] do 
    end
    resources :wage_reports, shallow: true do
      resources :wage_entries
    end
  end

  resources :tpas do
    get 'get_tpas'
  end

  # resources : do


  # end


  resources :settings do
    post 'create_role', to: 'settings#create_role', as: 'create_role'
    post 'create_key', to: 'settings#create_key', as: 'create_key'
    post 'create_permissions', to: 'settings#create_permissions', as: 'create_permissions'
    get 'get_roles', to: 'settings#get_roles'
    get 'get_keys', to: 'settings#get_keys'
    get 'get_permissions', to: 'settings#get_permissions'
    delete 'remove_role_and_permissions', to: 'settings#remove_role_and_permissions'
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employers/employer_factory.rb
module Employers
  class EmployerFactory
		def self.call(contact_info:, employer_info:, address_info:)
      employer = Parties::OrganizationParty.new(legal_name: employer_info.legal_name, fein: employer_info.fein, entity_kind: employer_info.kind.to_sym, is_foreign_entity: false)
      contact = Parties::PersonParty.new(current_first_name: contact_info.first_name, current_last_name: contact_info.last_name)

      employer.addresses.build address_info.attributes.except(:area_code, :number, :extension)

      relationship_party = Roles::RelationshipRoleFactory.new(contact, :contact, :organization_ui_primary_contact, employer).party

      if Parties::PartyRoleKind.is_valid_key?(employer_info.kind.to_sym)
        role = Roles::RoleFactory.new(employer, employer_info.kind.to_sym).party_role
      end

      financial_account = FinancialAccounts::FinancialAccountFactory.call(employer, account_kind: :ui_financial_account, initial_liability_date: Date.parse(employer_info.date_of_first_wages))

      #employee_party_role = Parties::PartyRole.new(party_role_kind: employee_party_role_kind, role_castable: employer)
      #employee.add_party_role(employee_party_role)
      [contact, employer, employer.party_ledger, relationship_party, role, financial_account].compact
    end

    def self.contact_role_kind
      @employee_party_role_kind ||= Parties::PartyRoleKind.find_by!(key: :contact)
    end

    def self.party_relationship_kind
      @employment_party_relationship_kind ||= Parties::PartyRelationshipKind.find_by!(key: :organization_ui_primary_contact)
    end
  end
end

app/models/employers/employer_form.rb
module Employers
  class AddressInfoForm
    include Virtus.model

    attribute :kind, String
    attribute :address_1, String
    attribute :address_2, String
    attribute :city, String
    attribute :state, String
    attribute :zip, String
    attribute :area_code, Integer
    attribute :number, Integer
    attribute :extension, Integer
  end

  class ContactInfoForm
    include Virtus.model

    attribute :first_name, String
    attribute :last_name, String
    attribute :dob, Date
    attribute :email, String
    attribute :area_code, Integer
    attribute :number, Integer
  end

  class EmployerInfoForm
    include Virtus.model

    attribute :legal_name, String
    attribute :dba, String
    attribute :fein, String
    attribute :kind, String
    attribute :sic_code, String
		attribute :company_type, String
		attribute :successor, String
		attribute :date_of_first_wages, String
  end

  class ContributionInfoForm
    include Virtus.model
  end

  class EmployerForm
    include Virtus.model
    include ActiveModel::Model

    attribute :id, String
    attribute :address_info, Employers::AddressInfoForm
    attribute :contact_info, Employers::ContactInfoForm
    attribute :contribution_info, Employers::ContributionInfoForm
    attribute :employer_info, Employers::EmployerInfoForm

    def self.for_new
      self.new
    end

    def self.for_create(params)
      form = self.new(params)
      #form.service.load_form_metadata(form)
      form
    end

    def service
      @service ||= EmployerService.new
    end

    def persist(update: false)
      return false unless self.valid?
      save_result, persisted_object = (update ? service.update(self) : service.save(self))
      return false unless save_result
      @show_page_model = persisted_object
      self.id = persisted_object.id.to_s
      true
    end

    def save
      persist
    end
  end
end

app/models/employers/employer_service.rb
module Employers
  class EmployerService
    attr_accessor :factory

    def initialize(attrs={})
      @factory = Employers::EmployerFactory
    end

    def save(form)
      model_attributes = form_params_to_attributes(form)
      objects = factory.call(model_attributes.except(:id))
      store(form, objects)
    end

		def form_params_to_attributes(form)
      form.attributes.except(:contribution_info)
		end

    def store(form, objects)
      objects.each do |object|
        object.save!
      end
    end
  end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  layout 'two_column', except: [:new]
  before_action :authenticate_user!

  def index
  end

  def new
    @employer = Employers::EmployerForm.for_new
  end

  def show
    @organization = Parties::OrganizationParty.find(params[:id])
    @account = @organization.party_ledger.financial_accounts.last

    render layout: 'two_column'
  end

  def get_employers
    @orgs = Parties::OrganizationParty.all.order(created_at: :desc)
    render json: { data: @orgs }
  end

  def create
    @employer = Employers::EmployerForm.for_create(contact_info: JSON.parse(form_params[:contact_info]), employer_info: JSON.parse(form_params[:employer_info]), address_info: JSON.parse(form_params[:address_info]))
    if @employer.save
      render json: {code: 200, message: @employer.id.to_s}
		else
			render json: {code: 400, message: 'Unable to process this request.'}
		end
  end

	private

	def form_params
		params.require(:employer).permit(:address_info, :contact_info, :employer_info)
	end
end

app/views/employers/index.html.erb
<div>
  <h3 class="display-5 text-center">Employers</h3>
  <div class="col-12" data-controller="employers">
    <table id="employerDataTable" class="display table table-stripped table-sm" style="width:100%">
        <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>FEIN</th>
                <th>Entity Kind</th>
            </tr>
        </thead>
    </table>
  </div>
</div>

app/views/employers/new.html.erb
<h4 class="text-center md-2 mt-4">Employer Registration</h4>
<div data-controller="employer-registrations">

  <!-- Validation wizard -->
  <div class="row" id="validation">
    <div class="col-12">
      <div class="card wizard-content">
        <div class="card-body">
          <%= form_for @employer, url: new_employer_path, html: { class: "validation-wizard wizard-circle", id:'employerFrom' } do |f| %>
            <!-- Step 1 -->
            <h6>Contact Info</h6>
            <section>
              <div class="row">
                <div class="col-md-4">
                  <div class="form-group">
                    <label for="wfirstName2"> First Name :
                      <span class="danger">*</span>
                    </label>
                    <input type="text" class="form-control required" id="wfirstName2" name="contact_info[first_name]"> </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label for="wlastName2"> Last Name :
                      <span class="danger">*</span>
                    </label>
                    <input type="text" class="form-control required" id="wlastName2" name="contact_info[last_name]"> </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label for="wdate2">Date of Birth :
                      <span class="danger">*</span>
                    </label>
                    <input type="date" class="form-control required" id="wdate2" name="contact_info[dob]"> </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-4">
                  <div class="form-group">
                    <label for="wemailAddress2"> Email Address :
                      <span class="danger">*</span>
                    </label>
                    <input type="email" class="form-control required" id="wemailAddress2" name="contact_info[email_address]"> </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label for="areaCode">Area Code :
                      <span class="danger">*</span>
                    </label>
                    <input type="tel" class="form-control required" id="areaCode" name="contact_info[area_code]" maxlength="3"> </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label for="wphoneNumber2">Phone Number :
                      <span class="danger">*</span>
                    </label>
                    <input type="tel" class="form-control required" id="wphoneNumber2" name="contact_info[phone_number]" maxlength="7"> </div>
                </div>
              </div>
            </section>
            <!-- Step 2 -->
            <h6>Address Info</h6>
            <section>
              <div class="row">
                <div class="col-md-9">
                  <div class="form-group">
                    <label for="address1">Address :
                      <span class="danger">*</span>
                    </label>
                    <input type="text" class="form-control required" id="address1" name="address_info[address_1]">
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="form-group">
                    <label for="kind1">Kind :
                      <span class="danger">*</span>
                    </label>
                    <select class="form-control required" id="kind1" name="kind1">
                      <option value="primary">Primary</option>
                      <option value="mailing">Mailing</option>
                      <option value="branch">Branch</option>
                    </select>
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-group">
                    <label for="address2">Address 2 :
                    </label>
                    <input type="text" class="form-control" id="address2" name="address_info[address_2]">
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="form-group">
                    <label for="city1">City :
                      <span class="danger">*</span>
                    </label>
                    <input type="text" class="form-control required" id="city1" name="address_info[city]">
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="form-group">
                    <label for="state1">State :
                      <span class="danger">*</span>
                    </label>
                    <select class="form-control required" id="state1" name="address_info[state]">
                      <option value="">SELECT STATE</option>
                      <option value="DC">DC</option>
                      <option value="MD">MD</option>
                      <option value="VA">VA</option>
                    </select>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="form-group">
                    <label for="zip1">Zip :
                      <span class="danger">*</span>
                    </label>
                    <input type="text" class="form-control required" id="zip1" name="address_info[zip]" maxlength="5">
                  </div>
                </div>
              </div>
            </section>
            <!-- Step 3 -->
            <h6>Company Info</h6>
            <section>
              <div class="row">
                <div class="col-md-4">
                  <div class="form-group">
                    <label for="legalNAme">Legal Name :
                      <span class="danger">*</span>
                    </label>
                    <input type="text" class="form-control required" id="legalName" name="employer_info[legal_name]">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label for="dba">DBA :
                    </label>
                    <input type="text" class="form-control" id="dba" name="employer_info[dba]">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label for="fein">FEIN :
                      <span class="danger">*</span>
                    </label>
                    <input type="text" class="form-control required" id="fein" name="employer_info[fein]" maxlength="9">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label for="kind">Kind :
                      <span class="danger">*</span>
                    </label>
                    <select class="form-control required" id="kind" name="employer_info[kind]">
                      <option value="">Select Entity Kind</option>
                      <%= options_for_select Parties::PartyRoleKind.where(:key.in => [:s_corporation, :c_corporation, :limited_liability_corporation, :limited_liability_partnership, :non_profit_501c3, :other_non_profit, :household_employer]).pluck(:title, :key).to_h %>
                    </select>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label for="companyType">Tax Reporting Type :
                      <span class="danger">*</span>
                    </label>
                    <select class="form-control required" id="companyType" name="employer_info[company_type]" data-action="change->employer-registrations#evidenceNeeded" data-target="employer-registrations.companyType">
                      <option value="">Tax Reporting Type</option>
                      <option value="contributor">Contributor</option>
                      <option value="reimbursable">Reimbursable</option>
                    </select>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label for="wdate3">Date of First Wages :
                      <span class="danger">*</span>
                    </label>
                    <input type="date" class="form-control required" id="wdate3" name="employer_info[date_of_first_wages]">
                  </div>
                </div>
                <div class="col-md-12 form-group d-none" data-target="employer-registrations.evidence">
                  <label for="exampleInputFile" class="bmd-label-floating">
                    Please provide evidence of your 501(c)(3) status
                  </label>
                  <input type="file" class="form-control-file" id="exampleInputFile">
                </div>
                <div class="col-md-12">
                  <label for="exampleInputFile" class="bmd-label-floating">
                    Is this organization a successor of a previous organization?
                  </label>
                  <div class="radio">
                    <label>
                      <input type="radio" name="optionsRadios" id="optionsRadios1" value="yes" data-target="employer-registrations.previousOrganization">
                      Yes
                    </label>
                  </div>
                  <div class="radio">
                    <label>
                      <input type="radio" name="optionsRadios" id="optionsRadios2" value="no" data-target="employer-registrations.previousOrganization">
                      No
                    </label>
                  </div>
                </div>
              </div>
            </section>
            <!-- Step 4 -->
            <h6>Contribution Info</h6>
            <section>
              <div class="row mb-3" data-target="employer-registrations.message"></div>
            </section>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employers/show.html.erb
<div class='row'>
  <div class='col-md-6 er-list-group'>
    <% @organization.party_ledger.financial_accounts.each do |account| %>
      <div class='row'>
        <div class='col'>
          <strong id="account-title"><%= account.title %></strong>
        </div>
      </div>
      <div class='row'>
        <div class = 'col'>
          <p class = "data-label">Opened On</p>
          <p><%= account.opened_on.strftime('%m/%d/%Y') %></p>
        </div>
      </div>
      <div class='row'>
        <div class = 'col'>
          <p class = "data-label">Status</p>
          <p><%= account.status.capitalize%></p>

        </div>
      </div>
      <div class='row'>
        <div class = 'col'>
          <p class = "data-label">Inital Liability Date</p>
          <p><%= account.initial_liability_date.strftime('%m/%d/%Y') %></p>

        </div>
      </div>
      <div class = 'row'>
        <div class = 'col'>
          <p  class="data-label">Current Contribution Rate</p>
          <p><%=  number_to_percentage(account.current_contribution_rate * 100, precision: 1)%></p>
        </div>
      </div>
      <div class='row'>
        <div class = 'col'>
          <p class="data-label">Current Wage Filing Schedule</p>
          <p><%= account.current_wage_filing_schedule == :uits_qtr_filer ? 'Quarterly' : 'Annually' %></p>
          </div>
      </div>
      <div class='row'>
          <div class = 'col'>
            <p class="data-label">Administrative Assesment Rate</p>
            <p><%= number_to_percentage(account.current_administrative_rate * 100, precision: 1)  %></p>
        </div>
      </div>
      <div class = 'row'>
        <div class = 'col'>
          <p class="data-label">Current Balance</p>
          <p><%= number_to_currency(account.current_balance)%></p>
        </div>
      </div>
      <div class='row'>
        <div class = 'col'>
        </div>
        <div class = 'col'>
        </div>
      </div>
    <% end %>
    <a href="https://ww2.e-billexpress.com/ebpp/MAConnector/" target="_blank"><button class="btn btn-raised btn-success">Make A Payment</button></a>
  </div>

  <div class="col-md-6">
    <div class="row">
      <div class="col-md-12">
        <strong>Notifications</strong>
      </div>
      <div class="col-md-12">
        <ul class="list-group">
          <li class="list-group-item"><a href="#">2019 Quarter 1 Wage Report (U3) are almost due</a></li>
          <li class="list-group-item"><a href="#">New Features for Employers are now available</a></li>
          <li class="list-group-item"><a href="#">2018 Annual Wage Reporting period is now closed</a></li>
        </ul>
        <br />
        <button class="btn btn-raised btn-success">Create New Notification</button>
      </div>
      <div class="col-md-12">
        <hr>
      </div>
      <div class="col-md-12">
        <strong>My Agent</strong>
      </div>
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-4">
            <i class="fas fa-address-card fa-9x"></i>
          </div>
          <div class="col-md-6">
            <ul class="list-group">
              <li class="list-group-item"><a href="#">Small Business Insurance Ltd.</a></li>
              <li class="list-group-item">John Smith</li>
              <li class="list-group-item">202-111-22222</li>
              <li class="list-group-item">john.smith@sbi.com</li>
            </ul>
            <br />
            <button class="btn btn-raised btn-secondary">Change</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>