config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v3 do
      get 'cupcakes/index'
    end
  end
  get 'subscriptions/index'
  get 'subscriptions/create'
  get 'subscriptions/new'
  get 'subscriptions/show'
  get 'subscriptions/update'
  devise_for :users
  get 'pages/home'
  get 'settings/home'

  mount Flipper::UI.app(Flipper.instance) => '/flipper'

  resources :dashboard

  resources :notifications

  resources :employers do
    get 'get_employers'
    resources :accounts, only: [:index] do 
    end
    resources :wage_reports, shallow: true do
      resources :wage_entries
    end
  end

  resources :tpas do
    get 'get_tpas'
  end

  # resources : do


  # end


  resources :settings do
    post 'create_role', to: 'settings#create_role', as: 'create_role'
    post 'create_key', to: 'settings#create_key', as: 'create_key'
    post 'create_permissions', to: 'settings#create_permissions', as: 'create_permissions'
    get 'get_roles', to: 'settings#get_roles'
    get 'get_keys', to: 'settings#get_keys'
    get 'get_permissions', to: 'settings#get_permissions'
    delete 'remove_role_and_permissions', to: 'settings#remove_role_and_permissions'
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Marketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <nav class="navbar uits-nav pt-1 pb-1">
      <span class="navbar-brand mb-0 h1">
        <img src="<%= asset_pack_path 'images/does.png' %>" width="60" height="20" class="d-inline-block align-top" alt="" />
        <span class="heading-txt">UITS</span>
      </span>
    </nav>
    <% if notice %>
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      <%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <% end %>
    <% if alert %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <%= alert %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <% end %>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <footer class="pt-2 pb-2 pl-3">
      <i class="fas fa-copyright"></i> 2019 IdeaCrew Inc
    </footer>
  </body>
</html>

app/views/layouts/two_column.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Marketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <nav class="navbar uits-nav pt-1 pb-1">
      <span class="navbar-brand mb-0 h1">
        <button class="navbar-toggler float-right" type="button" data-toggle="drawer" data-target="#dw-p1">
          <span class="sr-only">Toggle drawer</span>
          <i class="fas fa-bars"></i>
        </button>
        <span class="heading-txt">UITS</span>
      </span>
    </nav>
    <% if alert %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <%= alert %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <% end %>
    <div class="main-container">
      <div class="bmd-layout-container bmd-drawer-f-l bmd-drawer-in">
        <header class="bmd-layout-header">
          <div class="row ml-2">
            <ul class="nav navbar-nav">
              <li class="nav-item"></li>
            </ul>
          </div>
        </header>
        <div id="dw-p1" class="bmd-layout-drawer">
          <div id="side-menu" data-controller="menu">
            <ul class="list-group">
              <li class="list-group-item pr-1 side-menu-item" data-toggle="collapse" data-target="#myAccount" aria-expanded="true" aria-controls="collapseOne" id="my-account">My Account</li>
              <ul id="myAccount" class="collapse pl-0" aria-labelledby="headingOne" data-parent="#side-menu">
                <li class="list-group-item pb-0 pl-3 mb-1"><i class="fas fa-user"></i></i> My Profile</li>
                <li class="list-group-item pb-0 pl-3 mb-1"><i class="fas fa-envelope"></i> Messages</li>
                <li class="list-group-item pb-0 pl-3"><i class="fas fa-power-off"></i> <%= link_to "Log Out", destroy_user_session_path %></li>
                <hr class="mt-4">
              </ul>

              <li class="list-group-item pr-1" id="dashboard-menu"><i class="fas fa-home mr-3"></i> <%= link_to 'Dashboard', dashboard_index_path %>
              <li class="list-group-item pr-1" data-toggle="collapse" aria-expanded="true" aria-controls="collapseOne" id="employer-menu-option"><i class="fas fa-users mr-3"></i> <%= link_to 'Employers', employers_path %>
                <ul id="employers" class="collapse" aria-labelledby="headingOne" data-parent="#side-menu">
                  <li class="list-group-item pb-0 pl-0"><span id="employerName"></span></li>
                  <li class="list-group-item pb-0 pl-0"><a href="#" id="employerWageReport">Wage Reports</a></li>
                  <li class="list-group-item pb-0 pl-0"><a href="#" id="employerAccount">Accounts</a></li>
                  <li class="list-group-item pb-0 pl-0"><a href="#" id="employerProfile">Profile</a></li>
                </ul>
              </li>
              <li class="list-group-item pb-0 pl-3 mb-1" id="ee-employer"><i class="fas fa-user mr-3"></i></i>My Employer
                <ul class="list-group pl-5 p-0">
                  <li class="list-group-item pb-0 pl-0"><span id="er-name"></span></li>
                    <ul class="list-group pl-1 pt-0">
                      <li class="list-group-item pb-0 pl-2"><a href="#" id="ee-wage-report">Wage Reports</a></li>
                      <li class="list-group-item pb-0 pl-2"><a href="#" id="ee-account">Account</a></li>
                      <li class="list-group-item pb-0 pl-2"><a href="#" id="ee-profile">Profile</a></li>
                    </ul>
                </ul>
              </li>
              <li class="list-group-item pr-1" aria-controls="collapseOne" id="tpa-menu"><i class="fas fa-users mr-3"></i> <%= link_to 'TPAs', tpas_path %></li>
              <li class="list-group-item pr-1" id="notifications-menu"><i class="fas fa-comment-alt mr-3"></i><%= link_to 'Notifications', notifications_path %></li>
              <li class="list-group-item pr-1" id="menu-settings"><i class="fas fa-cogs mr-3"></i><%= link_to 'Settings', settings_home_path %></li>
            </ul>
          </div>

        </div>
        <main class="bmd-layout-content">
          <div class="container-fluid">
            <%= yield %>
          </div>
        </main>
      </div>
      <footer class="pt-2 pb-2 pl-3">
        <i class="fas fa-copyright"></i> 2019 IdeaCrew Inc
      </footer>
    </div>
  </body>
</html>